# Generated by Django 5.0.6 on 2024-05-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(max_length=100)),
                ('delivery_state_1', models.CharField(max_length=100)),
                ('delivery_state_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.IntegerField(max_length=100),
        ),
    ]
