# Generated by Django 5.0.6 on 2024-05-24 05:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_order_alter_test_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_quantity', models.PositiveIntegerField(default=1)),
                ('final_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('item_price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_state_1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_state_2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='final_destination',
            field=models.CharField(choices=[('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='final_payment_amount',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='initial_destination',
            field=models.CharField(choices=[('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='initial_payment_amount',
            field=models.FloatField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('N', 'Nagt'), ('C', 'Terminal'), ('O', 'Online')], default='N', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Jemlenýär'), ('D', 'Ýatyryldy'), ('H', 'Doly däl'), ('S', 'Üstünlikli')], default='P', max_length=50),
        ),
        migrations.AddField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.order'),
        ),
    ]
