# Generated by Django 5.0.6 on 2024-05-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_order_item_delete_test_remove_order_delivery_state_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='final_destination',
            new_name='final_dest',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='final_payment_amount',
            new_name='final_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='initial_destination',
            new_name='initial_dest',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='initial_payment_amount',
            new_name='initial_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_fee',
            new_name='service_fee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_time',
            new_name='time',
        ),
    ]
