# Generated by Django 5.0.6 on 2024-05-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_rename_order_code_order_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_center',
            field=models.BooleanField(default=False),
        ),
    ]
