# Generated by Django 5.0.6 on 2024-05-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_order_in_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='J', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='J', max_length=50),
        ),
    ]
