# Generated by Django 5.0.6 on 2024-05-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_alter_order_final_dest_alter_order_initial_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='final_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='J', max_length=50),
        ),
        migrations.AddField(
            model_name='order_item',
            name='initial_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='J', max_length=50),
        ),
    ]
