# Generated by Django 5.0.6 on 2024-05-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_alter_order_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_balance',
            field=models.BooleanField(default=True, verbose_name='Balansdamy?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='final_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], max_length=50, verbose_name='Barmaly ýeri'),
        ),
        migrations.AlterField(
            model_name='order',
            name='in_center',
            field=models.BooleanField(default=False, verbose_name='Merkezdemi?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('M', 'Mary'), ('A', 'Aşgabat'), ('L', 'Lebap'), ('D', 'Daşoguz'), ('B', 'Balkan')], default='J', max_length=50, verbose_name='Duran ýeri'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Asyl töleg'),
        ),
    ]
