# Generated by Django 5.0.6 on 2024-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0010_order_in_balance_alter_order_final_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Müşderiniň töläni'),
        ),
    ]
