# Generated by Django 5.0.6 on 2024-05-25 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_alter_order_final_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='cash_registers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kassanyň ady')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress')),
                ('balance', models.FloatField(default=0, verbose_name='Balans')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='final_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.cash_registers'),
        ),
    ]
