# Generated by Django 5.0.6 on 2024-05-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_cash_registers_alter_order_final_dest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_registers',
            options={'verbose_name': 'Kassa', 'verbose_name_plural': 'Kassalar'},
        ),
        migrations.AlterModelOptions(
            name='order_item',
            options={'verbose_name': 'Sargyt Harydy', 'verbose_name_plural': 'Sargyt Harytlary'},
        ),
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Müşderiniň töläni'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Asyl töleg'),
        ),
    ]
