# Generated by Django 5.0.6 on 2024-05-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_alter_cash_registers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.FloatField(default=0, max_length=50, verbose_name='Hyzmatyň bahasy'),
        ),
    ]
