# Generated by Django 5.0.6 on 2024-05-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_alter_order_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='final_quantity',
            field=models.PositiveIntegerField(blank=True, max_length=models.PositiveIntegerField(default=1, verbose_name='Harydyň mukdary'), null=True, verbose_name='Harydyň kabul edilen mukdary'),
        ),
    ]
