# Generated by Django 5.0.6 on 2024-05-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_alter_order_item_final_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='final_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Harydyň kabul edilen mukdary'),
        ),
    ]
