# Generated by Django 4.2.13 on 2024-06-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_alter_order_item_options_alter_order_final_dest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Kassanyň ady')),
                ('address', models.CharField(max_length=100, verbose_name='Adress')),
                ('balance', models.FloatField(verbose_name='Balans')),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(max_length=10)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.cash_registers')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalCash_registers',
        ),
    ]
