# Generated by Django 4.2.13 on 2024-06-05 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_historicalcash_registers_delete_cashregisterhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='in_center_update',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Merkeze geçen wagty'),
        ),
    ]
