# Generated by Django 4.2.13 on 2024-06-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_order_in_center_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='final_dest',
            new_name='cash_registry',
        ),
    ]
