# Generated by Django 4.2.13 on 2024-06-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_rename_final_dest_order_cash_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('Mary', 'Mary'), ('Aşgabat', 'Aşgabat'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Balkan', 'Balkan')], default='J', max_length=50, verbose_name='Barmaly ýeri'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='control.cash_registers', verbose_name='Kassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('Mary', 'Mary'), ('Aşgabat', 'Aşgabat'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Balkan', 'Balkan')], default='J', max_length=50, verbose_name='Duran ýeri'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='final_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('Mary', 'Mary'), ('Aşgabat', 'Aşgabat'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Balkan', 'Balkan')], max_length=50, verbose_name='Harydyň jemlenýän ýeri'),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='initial_dest',
            field=models.CharField(choices=[('J', 'Jemlenýär'), ('Mary', 'Mary'), ('Aşgabat', 'Aşgabat'), ('Lebap', 'Lebap'), ('Daşoguz', 'Daşoguz'), ('Balkan', 'Balkan')], max_length=50, verbose_name='Harydyň ýerleşýän ýeri'),
        ),
    ]
